export const SET_CITIES = 'SET_CITIES'
export const SET_AVAILABILITY = 'SET_AVAILABILITY'
export const SET_RESERVATION = 'SET_RESERVATION'
export const CLEAR_RESERVATIONS = 'CLEAR_RESERVATIONS'

// Api types
export const GET_AVAILABILITY = 'GET_AVAILABILITY'
